### ISSUE TITLE
Cannot create a new measurement set

### ISSUE THREAD

**Issue by cjordan** [pkgw/rubbl#114]
Hi @pkgw, I'm finally getting around to trying `rubbl` and making it work for me.  Unfortunately, I'm having trouble with the very basics (creating a MS) and I can't see how this is done in your existing code (e.g. `spwglue.rs`).  Here's a simple example:

```rust
// main.rs
use rubbl_casatables::{Table, TableOpenMode};

fn main() {
    let _t = Table::open("/tmp/test.ms", TableOpenMode::Create).unwrap();
    println!("Made a measurement set at /tmp/test.ms");
}
```

```toml
# Cargo.toml
[package]
name = "test-rubbl"
version = "0.1.0"
authors = ["Christopher H. Jordan <christopherjordan87@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rubbl_casatables = "^0.1.4"
```

```
cargo run
   Compiling test-rubbl v0.1.0 (/home/chj/Software/personal/test-rust/test-rubbl)
    Finished dev [unoptimized + debuginfo] target(s) in 1.98s
     Running `target/debug/test-rubbl`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: CasacoreError("Table /tmp/test.ms does not exist")', src/main.rs:4:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I've tried the other enum variants of `TableOpenMode` (i.e. `Read` and `ReadWrite`) but as expected, they don't work.  Am I missing something?

Also, while I have your attention, would you be interested in me having a go at tweaking your code?  In particular, I wonder if the thiserror crate will be tidier than failure.  It seems that failure doesn't implement `std::error::Error`.
