### ISSUE TITLE
`rubbl_core::Complex` cannot be compared using `approx::abs_diff_eq!`

### ISSUE THREAD

**Issue by derwentx** [pkgw/rubbl#169]
I have some tests that compare casa table cell values, some of which could be of type `num-complex::Complex<T>`. Unless I want to re-impl `CasaScalarData` et al. for my own `num-complex::Complex<T>`, I have to use `rubbl_core::Complex`, but this does not impl `AbsDiffEq` which is necessary for `approx::abs_diff_eq!`.

This can be fixed by ensuring modifying `core/Cargo.toml`

```toml
num-complex = { version = ">=0.3" }
approx = { version = ">=0.4", features = ["num-complex"] }
```
